[2022-07-18 13:50:27,088] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_dag.load manual__2022-07-18T13:50:17.454943+00:00 [queued]>
[2022-07-18 13:50:27,101] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_dag.load manual__2022-07-18T13:50:17.454943+00:00 [queued]>
[2022-07-18 13:50:27,101] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-18 13:50:27,101] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-18 13:50:27,101] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-18 13:50:27,120] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load> on 2022-07-18 13:50:17.454943+00:00
[2022-07-18 13:50:27,126] {standard_task_runner.py:52} INFO - Started process 2802 to run task
[2022-07-18 13:50:27,130] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'load', 'manual__2022-07-18T13:50:17.454943+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp67olxsvt', '--error-file', '/tmp/tmpssu5nhqp']
[2022-07-18 13:50:27,131] {standard_task_runner.py:80} INFO - Job 31: Subtask load
[2022-07-18 13:50:27,207] {task_command.py:371} INFO - Running <TaskInstance: etl_dag.load manual__2022-07-18T13:50:17.454943+00:00 [running]> on host 70b17816bd7e
[2022-07-18 13:50:27,312] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_dag
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2022-07-18T13:50:17.454943+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-18T13:50:17.454943+00:00
[2022-07-18 13:50:27,346] {logging_mixin.py:115} INFO -                                            song_name  ...                                          timestamp
0  [Avareh, Arezou, Tabiat, Setareh, Tasavor Kon,...  ...  [2022-07-18, 2022-07-17, 2022-07-17, 2022-07-1...

[1 rows x 4 columns]
[2022-07-18 13:50:27,347] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 107, in load
    song_df.to_csv(file_path,exist_ok=True)
TypeError: to_csv() got an unexpected keyword argument 'exist_ok'
[2022-07-18 13:50:27,359] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=etl_dag, task_id=load, execution_date=20220718T135017, start_date=20220718T135027, end_date=20220718T135027
[2022-07-18 13:50:27,377] {standard_task_runner.py:97} ERROR - Failed to execute job 31 for task load (to_csv() got an unexpected keyword argument 'exist_ok'; 2802)
[2022-07-18 13:50:27,422] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-18 13:50:27,510] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
